export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_AVAILABLE_KUDOS_SUCCESS = "GET_AVAILABLE_KUDOS_SUCCESS";
export const GET_MY_KUDOS_SUCCESS = "GET_MY_KUDOS_SUCCESS";
export const GET_TIMELINE_DATA_SUCCESS = "GET_TIMELINE_DATA_SUCCESS";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
